version: "3"
services:
  app:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo
    env_file:
      - .env
  mongo:
    image: mongo
    env_file:
      - .env
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27017:27017"
  mysql:
    image: mysql:5.7
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./mongo-volume:/var/lib/mysql